sudo: required
dist: trusty
language: php

php:
  - '5.6'
  - '7.0'
  - nightly
  - hhvm-3.12
  - hhvm-3.15

matrix:
    allow_failures:
        - php: hhvm-3.12
        - php: hhvm-3.15

install: composer install

script: phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)